server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leo95h/init-config-server
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'